[package]
name = "example-cache-simple"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
salvo = { workspace = true, features = ["cache"] }
tokio = { workspace = true, features = ["macros"] }
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
