export const featuresChildren = function (bookRoot: string) {
  return [
    `${bookRoot}/features/affix-state.md`,
    `${bookRoot}/features/basic-auth.md`,
    `${bookRoot}/features/cache.md`,
    `${bookRoot}/features/caching-headers.md`,
    `${bookRoot}/features/compression.md`,
    `${bookRoot}/features/cors.md`,
    `${bookRoot}/features/csrf.md`,
    `${bookRoot}/features/flash.md`,
    `${bookRoot}/features/force-https.md`,
    `${bookRoot}/features/jwt-auth.md`,
    `${bookRoot}/features/logging.md`,
    `${bookRoot}/features/openapi.md`,
    `${bookRoot}/features/proxy.md`,
    `${bookRoot}/features/rate-limiter.md`,
    `${bookRoot}/features/serve-static.md`,
    `${bookRoot}/features/session.md`,
    `${bookRoot}/features/size-limiter.md`,
    `${bookRoot}/features/sse.md`,
    `${bookRoot}/features/timeout.md`,
    `${bookRoot}/features/trailing-slash.md`,
    `${bookRoot}/features/websocket.md`,
  ];
}