name: CI

on:
  push:
    branches: [main]
    paths:
      - "codes/**"
  pull_request:
    branches: [main]
    paths:
      - "codes/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Cargo Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.89"

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: codes

      - name: cargo check
        working-directory: codes
        run: cargo check --workspace
